spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:${MONGO_URL:mongodb://localhost:27017/blackjack}}

  r2dbc:
    url: ${SPRING_R2DBC_URL}

  sql:
    init:
      mode: always

logging:
  level:
    com.blackjack: INFO
    org.springframework: WARN

server:
  port: ${PORT:8080}